### ISSUE TITLE
The extralight is 44,5% less taller.

### ISSUE THREAD

**Issue by fabiorug** [bcorporaal/Udon-mono#1]
For me that is an issue.

**Comment by fabiorug** [comment]
Should be clearer

**Comment by bcorporaal** [comment]
Thanks for sharing the issue, but I'm not sure I understand. Do you mean there is a height difference between the weights? If so, can you provide more details? If possible, also check if you have the same issue with the most recent release of [Iosevka](https://github.com/be5invis/Iosevka)? 

If I compare these weights, they are the same height.

<img width="712" alt="Screenshot 2024-01-14 at 16 19 25" src="https://github.com/bcorporaal/Udon-mono/assets/12683014/807f7eb5-7799-41eb-a397-262525af95dd">
<img width="712" alt="Screenshot 2024-01-14 at 16 19 33" src="https://github.com/bcorporaal/Udon-mono/assets/12683014/4db261b0-c374-4f5a-800a-03d6203ca864">
<img width="712" alt="Screenshot 2024-01-14 at 16 19 40" src="https://github.com/bcorporaal/Udon-mono/assets/12683014/4329a99b-e628-4029-9785-96d23822fe64">
![udon height comparison](https://github.com/bcorporaal/Udon-mono/assets/12683014/12a72dc8-005e-43a1-bf66-b438657d3433)

**Comment by fabiorug** [comment]
Update made a 9 per cent less taller fix the J.

**Comment by fabiorug** [comment]
The n should be LESS sharp the R could be made smaller

**Comment by fabiorug** [comment]
Update made a 8 per cent less taller fix the J.
